### ISSUE TITLE
This module stops to work today after latest laminas/laminas-servicemanager update to version 3.6.0

### ISSUE THREAD

**Issue by syberon** [neilime/twbs-helper-module#128]
This module stops to work today after latest laminas/laminas-servicemanager update to version 3.6.0+. All form elements renders with default Laminas view helpers instead of twbs helpers.

**To Reproduce**
1. Update laminas/laminas-servicemanager to latest version (3.6.1)
2. Run script that uses twbs form helpers

**Expected behavior**
Form elements renders with twbs view helpers

**Comment by syberon** [comment]
I found that the reason of this issue is bug in new version of ServiceManager. It overwrite all custom declared invokables with default values. The issue related to this problem is already opened for ServiceManager 4 days ago and marked as Bug. Now we only need to wait for the fix of this problem in ServiceManager and use older version 3.5.1 before this.

**Comment by neilime** [comment]
Thank you for the investigation @syberon
So we have to wait for https://github.com/laminas/laminas-servicemanager/issues/68 fix

**Comment by syberon** [comment]
The last update of laminas-servicemanager (3.6.2) fixes this issue.
