### ISSUE TITLE
Support for Bootstrap 5

### ISSUE THREAD

**Issue by syberon** [neilime/twbs-helper-module#165]
Hi, Emilien!

The Bootstrap 5 released a few days ago. Can you have a plans to update this module to support this version in near future?

**Comment by neilime** [comment]
Hi @syberon, I'm thinking about it.

The todo list:

- [ ] Check the diffs from v4 to estimate the workload
- [ ] Create a v4 branch to handle hotfixes for V4
- [ ] Implement v5

**Comment by syberon** [comment]
I already started to adapt current version to support V5. For now i modified a basic form elements view helpers (input, checkbox, select) with new v5 rules.
If you create a new branch i can provide some PRs to you.

**Comment by neilime** [comment]
Here is the branch: https://github.com/neilime/twbs-helper-module/tree/bootstrap-5

**Comment by syberon** [comment]
Hi, Emilien.
When do you plan to release this new version?

**Comment by neilime** [comment]
Hi @syberon, I'm waiting for merging this PR first: https://github.com/neilime/twbs-helper-module/pull/178

**Comment by neilime** [comment]
FYI, Bootstrap 5 PR is finally ready to be released, I will do it next week

**Comment by syberon** [comment]
> FYI, Bootstrap 5 PR is finally ready to be released, I will do it next week

Good news, Emilien! Thanks for you work!

**Comment by neilime** [comment]
Version 5.0.0 supporting Bootstrap 5 released: https://github.com/neilime/twbs-helper-module/releases/tag/v5.0.0
