### ISSUE TITLE
Possibility to disable "properIndentation"

### ISSUE THREAD

**Issue by lampi87** [neilime/twbs-helper-module#193]
Hi,

adding "ProperIndentation" leads to a bug in html structure in some rare cases. I'm not 100% sure how to reproduce this error with a generic example.

In my case, I have a very long form with one main fieldset containing two additional levels of fieldsets. For the second level of fieldsets the trailing "</div></div>" are missing. So the whole form structure is wrong.

After adding `return $sContent;` on line 53 in function `addProperIndentation` in `View/Helper/HtmlTrait.php` everything works fine.
Another possibility to fix this error is to comment out line 74 to line 92. So it may be a problem related to exploding lines (line 61)

I know this is a very unspecific description, but unfortunately I cannot provide more details.
It would be great if indentation can be disabled. Its a very annoying problem related to a "nice to have" clean html code.

Best regards
Alexander

**Comment by neilime** [comment]
Hi @lampi87,

Thank you for reporting this issue.

I can plan to add an option to disable de "proper indentation" option.

To resolve the issue, can you copy paste a exemple of broken html you have?

**Comment by lampi87** [comment]
Hi,

sorry for late reply. this is the output with originial HtmlTrait.php file:
```
<form method="post" name="formEditor" class=" layout-form-padding" role="form" id="formEditor">
    <fieldset disabled="disabled" class="form-group">
        <div class="row">
            <legend class="col-form-label">...</legend>
			<fieldset class="w-100">
                <div class="row">
                    <legend class="col-form-label">Gelenke</legend>
					<fieldset class="w-100">
                        <div class="row">
                            <legend class="col-form-label">...</legend>
                            <div class="col-sm-12">
                                <label for="...">...</label>
                                <input type="text" name="..." list="..." class="form-control" value="frei" autocomplete="off">
                            </div>
                        </div>
                    </fieldset>
					<fieldset class="w-100">
                        <div class="row">
                            <legend class="col-form-label">...</legend>
                            <div class="col-sm-12">
                                <label for="...">....</label>
                                <input type="text" name="..." list="..." class="form-control" value="frei" autocomplete="off">
                            </div>
                        </div>
                    *** </fieldset></div> MISSING HERE ***
        </fieldset></div>
    </fieldset>
</form>
```

**Comment by neilime** [comment]
@lampi87 I've create some tests to reproduce the issue but without succes I don't have any issue with the proper indentation function

https://github.com/neilime/twbs-helper-module/pull/219

Do you have the error with the very last version of the module?

If so can you please give the php code wich generate the form
