### ISSUE TITLE
Version 36.3 released in Packagist 

### ISSUE THREAD

**Issue by driehle** [neilime/twbs-helper-module#220]
**Describe the bug**
It seems like there happened a mistake in the release process and a version 36.3 has been release by accident. I was made aware of that as Dependabot notified me with a PR. 36.3 was released earlier than 3.6.8 (most likely as a typo of 3.6.3). 

**To Reproduce**
See 
https://packagist.org/packages/neilime/twbs-helper-module

**Expected behavior**
From my point of view you could simply delete the release on Packagist. However, that will cause issues for people who may have already updated. The other solution would be to continue with 37.0.0 as the next version.

**Comment by neilime** [comment]
I've removed the version on packagist
