### ISSUE TITLE
Fieldset label not displayed

### ISSUE THREAD

**Issue by becoded** [neilime/twbs-helper-module#293]
**Describe the bug**
The fieldset label for the radios aren't displayed

**To Reproduce**
https://neilime.github.io/twbs-helper-module/docs/usage/forms/layout/#horizontal-form

**Expected behavior**
Label should be positioned in front of the group.
See https://getbootstrap.com/docs/5.1/forms/layout/#horizontal-form

**Screenshots**
Actual:
![image](https://user-images.githubusercontent.com/458126/148858314-e8f029f4-1feb-4020-a90a-a8fe4bce5e11.png)

Expected:
![image](https://user-images.githubusercontent.com/458126/148858343-2347e4d0-7683-4402-b0a0-b060fc586392.png)

**Comment by neilime** [comment]
Fixed on https://github.com/neilime/twbs-helper-module/releases/tag/v5.0.1

**Comment by becoded** [comment]
Thx!  🙇‍♂️
