### ISSUE TITLE
Logo should be updated tp reflect the migration to Laminas

### ISSUE THREAD

**Issue by rarog** [neilime/twbs-helper-module#35]
Currently following asset is used as official logo: https://repository-images.githubusercontent.com/80362393/0286f600-fab3-11e9-9d0a-d76983616175

This doesn't reflect the migration to Laminas yet and should be changed.

**Comment by neilime** [comment]
Yes, it is scheduled before releasing next version

**Comment by bogal** [comment]
...and perhaps renaming the package to remove zf_.

**Comment by neilime** [comment]
I've think about it but don't find a nice name yet

**Comment by rarog** [comment]
Just in case of doubt it can always become "laminas-twbs-helper-module". :D

**Comment by bogal** [comment]
> 
> 
> Just in case of doubt it can always become "laminas-twbs-helper-module". :D

It's better. What about something like bootstrap flow. Or BootView. Or something completely unrelated, like blueberry.

**Comment by neilime** [comment]
Migration is done : https://github.com/neilime/twbs-helper-module/releases/tag/v3.0.0
