### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by JoseMPereira** [neilime/twbs-helper-module#38]
Can you add the possibility of adding custom sizes?

**Comment by neilime** [comment]
Can you please provide an example of you would like to do

**Comment by JoseMPereira** [comment]
Ok, i am using a template that i bought on the internet, its a template made with bootstrap 4 but they have add a custom size btn-xs, its mini buttons to use inside tables.
I have try add that size but i got an error saying size dont exist.
My question is: its possible to add custom sizes to the library?
thank you very much

**Comment by neilime** [comment]
Allowed sizes are same as supported by Twitter Boostrap, so ou cannont define custom size via `size` the option.

However you can set the class attribute with "btn-xs" of your button element.

```php
$oButton = new \Laminas\Form\Element\Button('custom-size', [
    'attributes' => ['class' => 'btn-xs'],
]);
```
