### ISSUE TITLE
Layout Horizontal not working?

### ISSUE THREAD

**Issue by CraigDSmith** [neilime/twbs-helper-module#440]
**Describe the bug**
Have not been able to make a form display in horizontal layout. Adding 

    $this->setOption('layout', \TwbsHelper\Form\View\Helper\Form::LAYOUT_HORIZONTAL);

to the form class  doesn't seem to work. The form is still displaying as inline. The class "row" is not added to the div.

**To Reproduce**
Steps to reproduce the behavior (have been using the Album tutorial to test):
create a form class and set the layout to horizontal 

    namespace Album\Form;

    use Laminas\Form\Form;

    class AlbumForm extends Form
    {
        public function __construct($name = null)
        {
        
             // This did not work
            //$options['layout'] = \TwbsHelper\Form\View\Helper\Form::LAYOUT_HORIZONTAL;
            //parent::__construct('album-form', $options);

            //this also did not work
            parent::__construct('album-form');
            $this->setOption('layout', \TwbsHelper\Form\View\Helper\Form::LAYOUT_HORIZONTAL);
        

Rendering the form in a view with:

    // module/Album/view/album/album/add.phtml:
    $title = 'Add new album';
    $this->headTitle($title);
    ?>
    <h1><?= $this->escapeHtml($title) ?></h1>
    <?php
    $form->setAttribute('action', $this->url('album', ['action' => 'add']));
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('title'));
    echo $this->formRow($form->get('artist'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();

**Expected behavior**
Expected :

    <div class="mb-3 row">
        <label class="form-label" for="title">Title</label>
        <input class="form-control" name="title" type="text" value="">

got: 

    <div class="mb-3">
        <label class="form-label" for="title">Title</label>
        <input class="form-control" name="title" type="text" value="">

**Additional context**
php: 8.0.8
laminas-form: 3.5.0
twbs-helper-module: 5.3.0
bootstrap 5.2.2

**Comment by neilime** [comment]
Hi @CraigDSmith,

Actually the behavior that pass the layout from for to element is done by the `TwbsHelper\Form\View\Helper\FormRows` helper, which is not so good I assume.

My opinion is that this process of inheriting options from form to element should be done by a dedicated method called by the `\TwbsHelper\Form\View\Helper\Form::prepare` method

**Comment by froschdesign** [comment]
> $form->setAttribute('action', $this->url('album', ['action' => 'add']));
> $form->prepare();
> 
> echo $this->form()->openTag($form);
> echo $this->formHidden($form->get('id'));
> echo $this->formRow($form->get('title'));
> echo $this->formRow($form->get('artist'));
> echo $this->formSubmit($form->get('submit'));
> echo $this->form()->closeTag();

This can be reduced to the following:

```php
$form->setAttribute('action', $this->url('album', ['action' => 'add']));
echo $this->form($form);
```

See also in the documentation of the _original_ form view helper: https://docs.laminas.dev/laminas-form/v3/helper/form/

**Comment by CraigDSmith** [comment]
@froschdesign Yes I know. Sometimes I choose to render the form elements individually for greater control over layout and appearance etc.

@neilime Still not working as expected. From what I can deduce,  In Form\View\Helper\FormRow.php getElementRowClasses() 

    $colum = $element->getOption('column'); 

is NULL so 

    $this->elementIsLayout($element, \TwbsHelper\Form\View\Helper\Form::LAYOUT_HORIZONTAL) 

never executes and the class  row is never added to $rowClasses.

Adding 

    if ($colum) {
        ....
    } else if ($this->elementIsLayout($element, \TwbsHelper\Form\View\Helper\Form::LAYOUT_HORIZONTAL)) {
        $rowClasses[] = 'row';
    }

allows the class row to be added, and it does produce:

    <div class="mb-3 row">
        <label class="form-label" for="title">Title</label>
        <input class="form-control" name="title" type="text" value="">

however the expected output in my initial post was incorrect. It should wrap a div around the form-control like so and add some default col classes, so expected output should be this:

    <div class="mb-3 row">
        <label class="form-label col-sm-2 " for="title">Title</label>
        <div class="col-sm-10">
            <input class="form-control" name="title" type="text" value="">
        </div>


I am migrating some zf2 and zf3 apps to laminas, that used your original Zf2-Twb-Bundle, which produces horizontal forms like so:

    <div class="form-group ">
        <label class="col-sm-2&#x20;control-label" for="title">Title</label>
        <div class=" col-sm-10">
            <input name="title" id="title" type="text" required="required" class="form-control" value="">
            <p class="help-block"></p>
        </div>
    </div>

**Comment by CraigDSmith** [comment]
Also have updated my form object to provide the css classes

        $this->add([
            'name' => 'id',
            'type' => 'hidden',
        ]);
        $this->add([
            'name' => 'title',
            'type' => 'text',
            'class'    => 'form-control',
            'attributes' => [
                'id'  => 'title',
                'required' => 'required',
            ],    
            'options' => [
                'label' => 'Title',
                'column-size' => 'sm-10',
                'label_attributes' => ['class' => 'col-sm-2'],
            ],
            
        ]);
        $this->add([
            'name' => 'artist',
            'type' => 'text',
            'class'    => 'form-control',
            'attributes' => [
                'id'  => 'artist',
                'required' => 'required',
            ],    
            'options' => [
                'label' => 'Artist',
                'column-size' => 'sm-10',
                'label_attributes' => ['class' => 'col-sm-2'],
            ],
        ]);
        $this->add([
            'name' => 'submit',
            'type' => 'submit',
            'attributes' => [
                'value' => 'Go',
                'id'    => 'submitbutton',
            ],
        ]);
