### ISSUE TITLE
Sample (documentation) dropdowns seems to be broken

### ISSUE THREAD

**Issue by cbichis** [neilime/twbs-helper-module#535]
Hi,

Dropdowns are not working:

https://neilime.github.io/twbs-helper-module/docs/usage/components/dropdowns/

Also tabs with dropdowns etc.

https://neilime.github.io/twbs-helper-module/docs/usage/components/navs-and-tabs/#tabs-with-dropdowns

**Comment by froschdesign** [comment]
The dropdown looks good:
![dropdown](https://github.com/neilime/twbs-helper-module/assets/103362/d073f70e-efc4-4f34-ae9d-854c2a2ec493)

But there some JavaScript errors, like:

```js
Uncaught TypeError: popoverTriggerList.map(...) is not a function
```

**Comment by cbichis** [comment]
Yes, got the same error in my console.

**Comment by neilime** [comment]
@cbichis thank you for reporting this issue on documentation website, it has been fixed.

**Comment by cbichis** [comment]
Thanks for your work!
