### ISSUE TITLE
Indentation breaks textarea content line-breaks (new lines) on htmlRender

### ISSUE THREAD

**Issue by KiwiJuicer** [neilime/twbs-helper-module#56]
**Describe the bug**

The "**addProperIndentation**" method in the HtmlTrait also idents the content of textareas (between element open and close tags).  [https://github.com/neilime/twbs-helper-module/blob/f02f14ebe529c8d0cf24c6b35f07a65dd7299903/src/TwbsHelper/View/Helper/HtmlTrait.php#L43](url)

Therefore all new lines ("**\n**") will on render change the original content of the element as you can see on the example screenshots.

**Expected behavior**
The content of <textarea></textarea> shall not be touched nor automatically idented

**Screenshots**
View:
![image](https://user-images.githubusercontent.com/3173659/81822300-3697a500-9533-11ea-886e-9666e8df8310.png)
In source code:
![image](https://user-images.githubusercontent.com/3173659/81823715-e1f52980-9534-11ea-9328-4bfb98d29b7c.png)

**Additional context**
I cannot find an easy way to fix this behavior but we need to find a quick fix by NOT try to ident in the case of a textarea. I'm not sure if there are even other cases where this behavior is not wanted.

**Comment by KiwiJuicer** [comment]
@neilime is there anything I can help?

**Comment by neilime** [comment]
@KiwiJuicer , I have pushed a fix on master (https://github.com/neilime/twbs-helper-module/commit/445fe3e4d9ec7c0ed7f5c9878e5d0f455419bfe8)

Please tell me if it works, if not I will need some context to improve Phpunit test (https://github.com/neilime/twbs-helper-module/blob/master/tests/TestSuite/TwbsHelper/View/Helper/HtmlTraitTest.php)

**Comment by KiwiJuicer** [comment]
@neilime Fix is working, result is as expected. Can you think of any cases this could apply other than textareas? Anyway, thanks for the quick fix. Will there be a new tag soon? It's been a while...

**Comment by neilime** [comment]
Thank you for your feedback.
I don't think there some other html elements that must be indentation free.

A new version has been released : https://github.com/neilime/twbs-helper-module/releases/tag/v3.1.0
