### ISSUE TITLE
Possibility to provide valid and invalid feedback

### ISSUE THREAD

**Issue by lampi87** [neilime/twbs-helper-module#62]
Is it possible to provide valid/invalid feedback on form creation? This feedback should be shown instead of browser default messages. As described here: https://getbootstrap.com/docs/4.5/components/forms/#validation

**Comment by neilime** [comment]
Hi @lampi87,

This now available with new version [v3.2.1](https://github.com/neilime/twbs-helper-module/releases/tag/v3.2.1).

You can find an example here: https://neilime.github.io/twbs-helper-module/demo.html#validation
