### ISSUE TITLE
Multicheckbox view helper is removing the hidden element

### ISSUE THREAD

**Issue by cbichis** [neilime/twbs-helper-module#649]
**Describe the bug**
The Laminas Form use_hidden_element option makes the view helper to prepend a hidden form input, which is useful for the case there is no selection for multi-checkbox. Possibly for other form elements but I havent tested.

However, TWBS helper module is not inserting this hidden form input if the option is set to true

**To Reproduce**

On TwbsHelper\Form\View\Helper\MultiCheckboxTrait by example the $tmpContent contains the hidden form element.

But this is stripped out of the final $content.

**Comment by froschdesign** [comment]
I think this part is meant:

https://github.com/neilime/twbs-helper-module/blob/cdb1af47cb49771d4200337ebda86be3dc6fe31e/src/TwbsHelper/Form/View/Helper/MultiCheckboxTrait.php#L43-L58

The corresponding tests do not contain anything for a hidden form element:

https://github.com/neilime/twbs-helper-module/blob/cdb1af47cb49771d4200337ebda86be3dc6fe31e/tests/TestSuite/TwbsHelper/Form/View/Helper/FormMultiCheckboxTest.php#L12-L39

**Comment by cbichis** [comment]
Yes.
