### ISSUE TITLE
After 3.2.0 I'm unable to group buttons from the form the form helper.

### ISSUE THREAD

**Issue by rarog** [neilime/twbs-helper-module#68]
Before just by calling `$this->form($myForm)` from my view I was able to render button groups just via options inside the \Laminas\Form\Form, with the change the call of group buttons logic was replaced by form rows. As far as I see there is no possibility to enforce button grouping from the form array notation and I would have to do manual assembling of the form.

Can the old behaviour be restored in parallel to the form row implementation?

**Comment by rarog** [comment]
Another thought - perhaps it would be a good compromise to be able to assemble the form using any of the available helpers using some generic structure.

I'll try to construct an example following this style form: https://docs.laminas.dev/laminas-form/quick-start/#factory-backed-form-extension

For example:
`
        $this->add([
            'type' => Element\Button::class,
            'name' => 'button1',
            'options' => [
                'label' => 'Button 1',
                'twbs-view-helper' => [
                    'helper' => 'buttonGroup',
                    'group' => 'my-button-group',
                    'options' => [
                        'column' => 'md-10',
                    ]
                ]
            ],
        ]);
        $this->add([
            'type' => Element\Button::class,
            'name' => 'button2',
            'options' => [
                'label' => 'Button 2',
                'twbs-view-helper' => [
                    'helper' => 'buttonGroup',
                    'group' => 'my-button-group',
                    'options' => [
                        'column' => 'md-10',
                    ]
                ]
            ],
        ]);
`

This should group the form elements by helper and key and result in an call of ButtonGroup->_invoke() with array of the two buttons and the options `['column' => 'md-10']` as second parameter.

This way any helper could be injected, that processes one or multiple elements. The same way I could inject buttonToolbar or any other helper to style multiple elements inside the form.

**Comment by neilime** [comment]
@rarog actually the "form button group" behaviour was a weird case, not well implemented, and didn't match with a Bootstrap documentation example.

That's why it has been removed.
I understand that it is needed, so I will (better) re-integrated it.

**Comment by neilime** [comment]
@rarog I've made a first implementation of button group rendering, you can check how to do it with this unit test: https://github.com/neilime/twbs-helper-module/blob/master/tests/TestSuite/TwbsHelper/Form/View/Helper/FormTest.php#L76

Does it fit with your need ?

**Comment by rarog** [comment]
It absolutely does fit my needs. I tried it out successfully and like how short and easy the notation is.

**Comment by neilime** [comment]
I have added this behaviours in documentation: https://neilime.github.io/twbs-helper-module/docs/rendering/forms/#button-groups
